org: ryanycw
app: ethtaipei-2023
service: ${env:SERVERLESS_SERVICE_NAME}
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ${env:AWS_REGION_DEV}
  profile: ${env:AWS_PROFILE_DEV} # profile of your aws credentials
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 29 # optional, in seconds, default is 6
  environment:
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents

          Resource: "*"

functions:
  zauktionBidProof:
    name: ${env:SERVERLESS_SERVICE_NAME}-${env:AWS_STAGE_DEV}-zauktion-bid-proof
    handler: src/handler.zauktionBidProof
    optimize:
      includePaths: ['src/zauktion.wasm', 'src/zauktion.zkey', 'src/idcheck.wasm', 'src/idcheck.zkey']
    events:
    - httpApi:
        path: /zauktion-bid-proof
        method: post

custom:
  dotenv:
    variableExpansion: false